CONFIG_NAME: 'MirrorGAN_original'


TRAIN:
  FLAG: TRUE
  NET_G: ''
  NET_E: 'STEM/text_encoder.pth'
  B_NET_D: False
  CAP_CNN: 'STREAM/original/cnn_encoder.pkl'
  CAP_RNN: 'STREAM/original/rnn_decoder.pkl'

  STREAM:
    USE_ORIGINAL: True
    HIDDEN_SIZE: 512
    NUM_LAYERS: 1

TEXT:
  EMBEDDING_DIM: 256