CONFIG_NAME: 'MirrorGAN_new'

TRAIN:
  FLAG: TRUE
  NET_G: ''
  NET_E: 'STEM/text_encoder.pth'
  B_NET_D: False
  CAP_CNN: 'STREAM/new/cnn_encoder.pkl'
  CAP_RNN: 'STREAM/new/rnn_decoder.pkl'

  STREAM:
    USE_ORIGINAL: False

TEXT:
  EMBEDDING_DIM: 256